fix: update deployment directory path in CI/CD workflow
- Changed the deployment directory path in the production CI/CD workflow from `/apps/fe/ihsanmuh/` to `~/apps/fe/ihsanmuh/` to ensure correct navigation during deployment.

diff --git a/.github/workflows/prod-cd.yml b/.github/workflows/prod-cd.yml
--- a/.github/workflows/prod-cd.yml
+++ b/.github/workflows/prod-cd.yml
@@ -33,7 +33,7 @@ jobs:
             echo "Starting deployment..."
 
             # Navigate to the application directory
-            cd /apps/fe/ihsanmuh/ || (echo "Directory not found!" && exit 1)
+            cd ~/apps/fe/ihsanmuh/ || (echo "Directory not found!" && exit 1)
 
             # Pull the latest image from Docker Hub
             echo "Pulling latest Docker image..."
